DROP TABLE IF EXISTS TAREFA;
CREATE TABLE TAREFA(
id_tarefa INT NOT NULL AUTO_INCREMENT,
titulo VARCHAR(255) NOT NULL,
id_projeto INT,
PRIMARY KEY(id_tarefa),
 FOREIGN KEY (id_projeto) REFERENCES PROJETO(id_projeto)
);